export const GET_SITTERS_REQUEST = 'GET_SITTERS_REQUEST'
export const GET_SITTERS_SUCCESS = 'GET_SITTERS_SUCCESS'
export const GET_SITTERS_FAIL = 'GET_SITTERS_FAIL'
export const SET_SITTERS = 'SET_SITTERS'
export const FILTER_SITTERS_REQUEST = 'FILTER_SITTERS_REQUEST'
export const FILTER_SITTERS_SUCCESS = 'FILTER_SITTERS_SUCCESS'
export const FILTER_SITTERS_FAIL = 'FILTER_SITTERS_FAIL'

